#! /usr/local/bin/python
# -*- coding: utf-8 -*-

import chess
import chess.uci
import sys

pieces = {
  'k':'♔',
  'q':'♕',
  'r':'♖',
  'b':'♗',
  'n':'♘',
  'p':'♙',
  'K':'♚',
  'Q':'♛',
  'R':'♜',
  'B':'♝',
  'N':'♞',
  'P':'♟'
}

board = chess.Board()
moves = []
engine = chess.uci.popen_engine('engines/stockfish')
engine.uci()

def print_board(board):

  def write(string):
    sys.stdout.write(string)

  def print_rank(i):
    print str(8-i) + ' ',

  def print_files():
    print ' ',
    for col in range(8):
      print chr(97 + col),
    print

  rows = board.fen().split()[0].split('/')
  for i in range(len(rows)):
    print_rank(i)
    for symbol in rows[i]:
      if symbol in pieces:
        write(pieces[symbol] + ' ')
      elif symbol in '12345678':
        write(int(symbol) * '· ')
    print
  print_files()

print_board(board)

while True:
  try:
    cmd = raw_input('! ')
  except EOFError:
    print
    break
  if cmd == 'resign':
    break
  elif cmd == 'moves':
    for i in range(len(moves)):
      if i % 2 == 0:
        print '{0}. {1}'.format((i / 2) + 1, moves[i]),
      else:
        print moves[i]
    print
  elif cmd == 'advice':
    engine.position(board)
    best, ponder = engine.go(movetime=500)
    analysis_board = chess.Board(board.fen())
    analysis_board.push(best)
    print "try:", board.san(best)
    print "watch out for:", analysis_board.san(ponder)
  elif cmd == 'board':
    print_board(board)
  else:
    try:
      move = cmd
      board.push_san(move)
    except ValueError:
      print 'Invalid or ambiguous move. Try again'
      print
      continue
    print_board(board)
    moves.append(move)
    if board.is_checkmate():
      print '#checkmate'
      break
    elif board.is_check():
      print '+check'
    elif board.is_stalemate():
      print 'stalemate'
      break
